site_name: iupitermag

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - Validation: 'validation.md'
  - 'Modules':
    - Internal Field: 'modules/internal.md'
    - Current Sheet: 'modules/currentsheet.md'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js